Modifid scripts to work against S3 (using BES gateway_handler) or local files based on invocation.

diff --git a/shell/aggEmulator/aggTestProcessor b/shell/aggEmulator/aggTestProcessor
--- a/shell/aggEmulator/aggTestProcessor
+++ b/shell/aggEmulator/aggTestProcessor
@@ -36,16 +36,33 @@ if [ $verbose = 1 ] ; then echo "FILES_LIST: $FILES_LIST"; fi
 BES_CONF=$prefix/etc/bes/bes.conf
 if [ $verbose = 1 ] ; then echo "BES_CONF: $BES_CONF"; fi
 
-SPACE=gateway
-if [ $verbose = 1 ] ; then echo "SPACE: $SPACE"; fi
+if [ $verbose = 1 ] ; then echo "TARGET: $TARGET"; fi
 
+if [ "$TARGET" = "S3_GATEWAY" ] ; then
+    
+    SPACE=gateway
+    if [ $verbose = 1 ] ; then echo "SPACE: $SPACE"; fi
+    
+    BUCKET_URL="http://cloudydap.s3.amazonaws.com"
+    if [ $verbose = 1 ] ; then echo "BUCKET_URL: $BUCKET_URL"; fi
+    
+    COLLECTION_URL="$BUCKET_URL/$COLLECTION"
+    if [ $verbose = 1 ] ; then echo "COLLECTION_URL: $COLLECTION_URL"; fi
 
-BUCKET_URL="http://cloudydap.s3.amazonaws.com"
-if [ $verbose = 1 ] ; then echo "BUCKET_URL: $BUCKET_URL"; fi
+elif [ "$TARGET" = "LOCAL" ] ; then
 
-COLLECTION_URL="$BUCKET_URL/$COLLECTION"
-if [ $verbose = 1 ] ; then echo "COLLECTION_URL: $COLLECTION_URL"; fi
+    SPACE=catalog
+    if [ $verbose = 1 ] ; then echo "SPACE: $SPACE"; fi
+        
+    COLLECTION_URL="/$COLLECTION";
+    if [ $verbose = 1 ] ; then echo "COLLECTION_URL: $COLLECTION_URL"; fi
+    
+else 
+    echo "ERROR: Production target must be either 'S3_GATEWAY' or 'LOCAL' ";
+    exit 2;
+fi
 
+  
 
 COLLECTION_FILE_NAMES=`cat $FILES_LIST`
 if [ $verbose = 1 ] ; then echo "Located "`echo $COLLECTION_FILE_NAMES | wc -w `" files."; fi
